version: '3.8'

services:
  contract-analysis:
    build: .
    container_name: contract-analysis-app
    ports:
      - "8501:8501"
    environment:
      # Pass environment variables from your .env file
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - ANTHROPIC_MODEL=${ANTHROPIC_MODEL:-claude-3-5-sonnet-20241022}
      - ANTHROPIC_MAX_TOKENS=${ANTHROPIC_MAX_TOKENS:-1500}
      - ANTHROPIC_TEMPERATURE=${ANTHROPIC_TEMPERATURE:-0.3}
    volumes:
      # Optional: Mount directory for file uploads persistence
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8501/_stcore/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.25'

volumes:
  uploads: